[phases.setup]
nixPkgs = ["nodejs", "npm", "postgresql"]

[phases.install]
cmds = ["cd backend && npm ci --only=production", "cd ../frontend && npm ci --only=production"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && npm run start:prod"
